import { CSSProperties } from 'react';
import { UI_COLORS } from '../constants';

export const styles: { [key: string]: CSSProperties } = {
  appContainer: { display: 'flex', flexDirection: 'column', height: '100vh', backgroundColor: UI_COLORS.background },
  header: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '0 24px', height: 60, backgroundColor: UI_COLORS.surface, borderBottom: `1px solid ${UI_COLORS.border}`, flexShrink: 0 },
  headerTitle: { fontSize: '1.5rem', color: UI_COLORS.primary, margin: 0 },
  headerControls: { display: 'flex', alignItems: 'center', gap: '16px' },
  listeningStatus: { margin: 0, fontStyle: 'italic' },
  micButton: { background: 'none', border: 'none', cursor: 'pointer', padding: 8, borderRadius: '50%', display: 'flex' },
  mainLayout: { display: 'flex', flexGrow: 1, overflow: 'hidden' },
  sidebar: { width: 240, backgroundColor: UI_COLORS.surface, borderRight: `1px solid ${UI_COLORS.border}`, padding: '16px 0', display: 'flex', flexDirection: 'column', gap: '8px' },
  content: { flexGrow: 1, overflowY: 'auto', padding: 24 },
  navItem: { display: 'flex', alignItems: 'center', gap: '16px', padding: '12px 24px', border: 'none', background: 'none', width: '100%', textAlign: 'left', cursor: 'pointer', fontSize: '1rem', color: UI_COLORS.textSecondary },
  navItemActive: { backgroundColor: UI_COLORS.primary + '1A', color: UI_COLORS.primary, fontWeight: 500 },
  navItemLabel: { whiteSpace: 'nowrap' },
  viewContainer: { maxWidth: 1200, margin: '0 auto' },
  grid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(250px, 1fr))', gap: '24px', marginBottom: 24 },
  card: { backgroundColor: UI_COLORS.surface, padding: '24px', borderRadius: 8, boxShadow: '0 2px 4px rgba(0,0,0,0.05)' },
  cardTitle: { marginTop: 0, marginBottom: 16, borderBottom: `1px solid ${UI_COLORS.border}`, paddingBottom: 8 },
  cardContent: { color: UI_COLORS.textSecondary },
  statBig: { fontSize: '2.5rem', fontWeight: 700, margin: 0, color: UI_COLORS.primary },
  statSmall: { fontSize: '1.2rem', fontWeight: 500, margin: 0, color: UI_COLORS.text },
  fullWidthCard: { gridColumn: '1 / -1' },
  logList: { listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '8px' },
  monitoringLayout: { display: 'flex', gap: '24px', height: 'calc(100vh - 60px - 48px)'},
  videoContainer: { flex: 2, display: 'flex', flexDirection: 'column', gap: 16, backgroundColor: '#000', borderRadius: 8, padding: 16 },
  videoFeed: { width: '100%', height: 'auto', flexGrow: 1, objectFit: 'cover', borderRadius: 8 },
  monitoringControls: { display: 'flex', justifyContent: 'center', gap: 16 },
  actionButton: { padding: '12px 24px', fontSize: '1rem', border: 'none', borderRadius: 8, cursor: 'pointer', color: '#fff', display: 'flex', alignItems: 'center', gap: 8, backgroundColor: UI_COLORS.primary },
  activityFeed: { flex: 1, backgroundColor: UI_COLORS.surface, borderRadius: 8, padding: 16, overflowY: 'auto' },
  feedTitle: { marginTop: 0 },
  modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000 },
  modalContent: { background: '#fff', padding: 24, borderRadius: 8, width: '90%', maxWidth: 500, boxShadow: '0 4px 15px rgba(0,0,0,0.2)' },
  modalHeader: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: `1px solid ${UI_COLORS.border}`, paddingBottom: 16, marginBottom: 16 },
  modalCloseButton: { background: 'none', border: 'none', fontSize: '1.5rem', cursor: 'pointer' },
  modalBody: { },
  textarea: { width: 'calc(100% - 20px)', padding: 10, fontSize: '1rem', borderRadius: 4, border: `1px solid ${UI_COLORS.border}`, marginBottom: 16, resize: 'vertical' },
  prescriptionForm: { display: 'flex', gap: '16px', flexWrap: 'wrap' },
  input: { flex: '1 1 150px', padding: '12px', fontSize: '1rem', borderRadius: 4, border: `1px solid ${UI_COLORS.border}` },
  table: { width: '100%', borderCollapse: 'collapse', marginTop: '16px' },
  th: { borderBottom: `2px solid ${UI_COLORS.border}`, padding: '12px', textAlign: 'left', color: UI_COLORS.text },
  td: { borderBottom: `1px solid ${UI_COLORS.border}`, padding: '12px', color: UI_COLORS.textSecondary },
  loginContainer: { display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '100vh', backgroundColor: UI_COLORS.background },
  loginCard: { backgroundColor: UI_COLORS.surface, padding: '40px', borderRadius: 12, boxShadow: '0 4px 20px rgba(0,0,0,0.1)', width: '100%', maxWidth: 400 },
  loginForm: { display: 'flex', flexDirection: 'column' as const, gap: 16 },
  loginInput: { padding: '12px 16px', fontSize: '1rem', borderRadius: 8, border: `1px solid ${UI_COLORS.border}`, outline: 'none', ':focus': { borderColor: UI_COLORS.primary } },
  loginButton: { padding: '12px 24px', fontSize: '1rem', fontWeight: 600, borderRadius: 8, border: 'none', backgroundColor: UI_COLORS.primary, color: '#fff', cursor: 'pointer' },
  errorBox: { padding: '12px', backgroundColor: '#f8d7da', border: `1px solid ${UI_COLORS.danger}`, borderRadius: 4 },
};

